### PR TITLE
Update internationalization functions.

### PR DESCRIPTION
**Pull request by mayukojpn**
* Translations should be done by `__()` instead of `translate()` https://developer.wordpress.org/reference/functions/translate/
* Text domain should match with plugin directory name. https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains

### CODE REVIEW

**Comment by mayukojpn** [comment]
Thanks @LasseRafn! If possible, please update wordpress.org SVN repo until 14 September. I'd like to introduce your plugin during my talk at WordCamp Tokyo!

Translation string will appear here after around a half day from sending commit.
https://translate.wordpress.org/projects/wp-plugins/wp-initials-avatar

**Comment by LasseRafn** [comment]
I'm honored, thanks @mayukojpn! I will have it updated by tonight, when I'm home. I appreciate this a lot.

**Comment by LasseRafn** [comment]
Good luck on your talk! Would ask if its going to be available for watching online, however my Japanese skills aren't exactly.. existing.

**Comment by mayukojpn** [comment]
I made another request 😱 https://github.com/LasseRafn/wordpress-initials-avatar/pull/9

My talk will be recorded and published on wordpress.tv later! You'll see a hundred avatars on the site, so you'll enjoy it without language ;)

**Comment by LasseRafn** [comment]
!! 🔥 

Sounds amazing! ;) I'm glad. Can't wait.

**Pull request merged**
